FROM golang:latest

ARG PG_USERNAME
ARG PG_PASSWORD
ARG PG_HOST
ARG PG_DATABASE
ARG PG_TABLE

ENV PG_USERNAME=${PG_USERNAME}
ENV PG_PASSWORD=${PG_PASSWORD}
ENV PG_HOST=${PG_HOST}
ENV PG_DATABASE=${PG_DATABASE}
ENV PG_TABLE=${PG_TABLE}

RUN mkdir /app
ADD . /app
WORKDIR /app
RUN go build -o main .
CMD ["/app/main"]